# Updates wizemen binaries if there are new binaries available.
name: Update binaries

# Controls when the workflow will run
on:
  # When manually requested
  workflow_dispatch:

jobs:
  update_windows:
    runs-on: ubuntu-latest
    steps:
      # Git
      - uses: actions/checkout@v2

      # Node environment
      - uses: actions/setup-node@v2
    
        with:
          node-version: 16.8.0
          
      - run: npm install
      - run: | 
          npm install
          node src/update-windows.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update windows binaries"
          git push
  update_mac:
    runs-on: ubuntu-latest
    steps:
      # Git
      - uses: actions/checkout@v2

      # Node environment
      - uses: actions/setup-node@v2
    
        with:
          node-version: 16.8.0
      
      - name: Run node script and commit files
        run: | 
           npm install
           node src/update-mac.js
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add .
           git commit -m "Update mac binaries"
           git push
    
