# Updates wizemen binaries if there are new binaries available.
name: Update binaries

# Controls when the workflow will run
on:
  # When manually requested
  workflow_dispatch:

jobs:
  update_windows:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Node environment
      - uses: actions/setup-node@v2
    
        with:
          node-version: 16.8.0
          
      - run: npm install
      - run: node src/update-windows.js
  update_osx:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Node environment
      - uses: actions/setup-node@v2
    
        with:
          node-version: 16.8.0
          
      - run: npm install
      - run: node src/update-mac.js
    
