# Updates wizemen binaries if there are new binaries available.
name: Update binaries

# Controls when the workflow will run
on:
  # When manually requested
  workflow_dispatch:

jobs:
  setup_git:
    runs-on: ubuntu-latest
    steps:
      # Git
      - uses: actions/checkout@v2

      - name: Run node script and commit files
        run: | 
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
  update_windows:
    needs: setup_git
    runs-on: ubuntu-latest
    steps:
      # Git
      - uses: actions/checkout@v2

      # Node environment
      - uses: actions/setup-node@v2
    
        with:
          node-version: 16.8.0
          
      - run: npm install
      - run: node src/update-windows.js
  update_mac:
    needs: setup_git
    runs-on: ubuntu-latest
    steps:
      # Git
      - uses: actions/checkout@v2

      # Node environment
      - uses: actions/setup-node@v2
    
        with:
          node-version: 16.8.0
      
      - name: Run node script and commit files
        run: | 
           npm install
           node src/update-mac.js
           git add .
           git commit -m "Update mac binaries"
           git push
    
